In [3]:
import numpy as np
import cvxpy as cp

In [4]:
# test 

m = 15
n = 10
np.random.seed(1)
s0 = np.random.randn(m)
lamb0 = np.maximum(-s0, 0)
s0 = np.maximum(s0, 0)
x0 = np.random.randn(n)
A = np.random.randn(m, n)
b = A @ x0 + s0
c = -A.T @ ldamb0

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A @ x <= b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)


The optimal value is -15.220912605552899
A solution x is
[-1.10133381 -0.16360111 -0.89734939  0.03216603  0.6069123  -1.12687348
  1.12967856  0.88176638  0.49075229  0.8984822 ]
A dual solution is
[6.98804877e-10 6.11756416e-01 5.28171747e-01 1.07296862e+00
 3.93758939e-09 2.30153870e+00 4.25704139e-10 7.61206896e-01
 8.36906241e-09 2.49370377e-01 1.30187061e-09 2.06014070e+00
 3.22417207e-01 3.84054343e-01 1.59493664e-09]


In [28]:
#create random packing instance

#idea: choose each column by picking 3 random entries.
n = 10
m = 4
A = []
for i in range(m):
    row = [1,1,1]
    row.extend([0 for i in range(n-3)])
    row = np.array(row)
    np.random.shuffle(row)
    A.append(row)
    
A = np.array(A)

A = A.T
print(A, np.shape(A))

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 1]] (10, 4)


In [62]:
# now create the LP.

n = 21
m = 41
A = []
for i in range(m):
    row = [1,1,1]
    row.extend([0 for i in range(n-3)])
    row = np.array(row)
    np.random.shuffle(row)
    A.append(row)
    
A = np.array(A)

A = A.T
#print(A, np.shape(A))

x = cp.Variable(m)
b = np.ones(n)
#print(b)
c = np.ones(m)
#print(c)

prob = cp.Problem(cp.Maximize(c.T@x),[A @ x <= b,x>=0])

prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)

#should use sage to get the actual denominator. Do get some weird looking stuff, just not sure what the denom is.
#for sure not a multiple of 1/3.


The optimal value is 6.521739130428669
A solution x is
[ 4.22784589e-12  5.20236434e-12  5.97371234e-12  8.26086957e-01
  8.14632945e-13  8.69565217e-02 -7.59492514e-13  3.04347826e-01
  9.13043478e-01  1.73913043e-01  5.08496830e-12  5.65217391e-01
  1.30434783e-01 -1.75632169e-12  8.69565217e-01  3.04347826e-01
  8.26086957e-01  1.30434783e-01 -1.63824056e-13 -1.59443539e-12
  6.95652174e-01  8.69565216e-02  2.52507969e-11  4.34782609e-02
  9.54656326e-13  3.82106275e-12  1.48894217e-12  2.20264245e-11
  1.81838348e-11  2.58829011e-11  3.73616479e-11  3.35307201e-11
  3.04347826e-01 -1.26148162e-12  3.42170524e-11  7.34817125e-12
  1.73913043e-01  4.82864896e-12  3.73432263e-12  8.69565217e-02
  7.19002983e-13]
A dual solution is
[4.78260870e-01 3.47826087e-01 4.34782609e-01 2.99051831e-01
 3.53122082e-01 4.89801031e-01 5.21739130e-01 1.73913043e-01
 4.78260870e-01 3.76218339e-12 2.99051831e-01 2.60869565e-01
 3.04347826e-01 3.04347826e-01 2.11147138e-01 4.78260870e-01
 3.04347826e-